In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### <b> Constructing Dataframe for Biometric Data - 1st Iteration </b>

##### <b> Main Biometric Data </b>

In [4]:
# Biometry dataframe
biometric_df = pd.read_csv("../../data/biom_mod.csv", delimiter=';')
biometric_df["Date"] = pd.to_datetime(biometric_df["Date"], format="%d/%m/%Y") #Convert Date column values to datatime datatype

In [5]:
#Setting column Date as the index
biometric_df.set_index("Date", inplace=True)

In [6]:
# List of all of the days biometry samples were taken
biom_dates_list = biometric_df.index.unique().tolist()
biom_dates_list, len(biom_dates_list)

([Timestamp('2024-09-07 00:00:00'),
  Timestamp('2024-09-11 00:00:00'),
  Timestamp('2024-09-14 00:00:00'),
  Timestamp('2024-09-17 00:00:00'),
  Timestamp('2024-09-20 00:00:00'),
  Timestamp('2024-09-24 00:00:00'),
  Timestamp('2024-09-29 00:00:00'),
  Timestamp('2024-10-03 00:00:00')],
 8)

##### <b> Biometric Labels </b>

In [7]:
# Labels dataframe
bbch_labels_df = pd.read_excel("../../raw_data/biom_to_BBCH.xlsx")

In [8]:
bbch_labels_df[0:45]

,Number,Line,Sample,CODE,2024-09-07 00:00:00,2024-09-11 00:00:00,2024-09-14 00:00:00,2024-09-17 00:00:00,2024-09-20 00:00:00,2024-09-24 00:00:00,2024-09-29 00:00:00,2024-10-03 00:00:00
0,1,1,W,RWGRB5,19,19,19,19,19,37,39,44
1,2,1,W,RWGRA3,19,19,19,19,19,19,19,19
2,3,1,W,RWGRC1,19,19,35,19,19,37,37,39
3,4,1,W,RWGRA2,19,19,19,19,19,19,19,19
4,5,1,W,RWGRB3,19,19,19,19,19,19,19,19
5,6,1,W,RWGRA4,19,19,19,19,19,19,18,19
6,7,1,W,RWGRC3,19,19,19,19,19,37,37,39
7,8,1,W,RWGRA5,19,19,19,19,19,19,19,19
8,9,2,W,RWGRC2,19,19,37,37,37,37,39,44
9,10,2,W,RWGRB4,19,19,19,19,19,19,19,19
10,11,2,W,RWGRC5,19,19,19,19,19,19,19,19
11,12,2,W,RWGRB1,19,19,19,37,37,39,39,45
12,13,2,W,RWGRC4,19,19,19,19,37,37,37,45
13,14,2,W,RWGRB2,17,19,19,19,17,19,17,19
14,15,2,W,RWGRA1,19,19,19,19,19,19,19,19
15,16,3,N,RNGRA3,19,19,19,19,19,19,19,19
16,17,3,N,RNGRB5,19,19,19,37,37,39,39,46
17,18,3,N,RNGRC4,19,19,19,37,37,39,39,45
18,19,3,N,RNGRA1,19,19,19,37,37,39,39,44
19,20,3,N,RNGRC5,19,19,19,19,37,37,39,44
20,21,3,N,RNGRB2,19,19,19,19,19,39,46,46
21,22,3,N,RNGRA2,19,19,19,19,19,19,19,19
22,23,4,N,RNROB2,16,16,19,19,19,19,19,19
23,24,4,N,RNROC3,17,19,19,19,19,19,16,17
24,25,4,N,RNROA5,14,16,17,17,18,18,19,18
25,26,4,N,RNROC5,17,19,19,19,18,19,16,17
26,27,4,N,RNROB3,15,18,18,19,19,19,18,19
27,28,4,N,RNROA1,13,13,15,14,15,16,16,18
28,29,4,N,RNROC1,15,18,19,19,19,19,16,17
29,30,5,N,RNGRC1,19,19,19,37,39,39,44,45
30,31,5,N,RNGRB3,19,19,19,37,37,39,39,44
31,32,5,N,RNGRA5,17,19,19,19,19,19,16,18
32,33,5,N,RNGRB1,19,19,19,19,19,19,18,19
33,34,5,N,RNGRC3,19,19,19,37,37,37,39,44
34,35,5,N,RNGRB4,19,19,19,19,19,19,19,19
35,36,5,N,RNGRA4,17,18,19,19,19,19,19,19
36,37,5,N,RNGRC2,19,19,19,19,19,19,19,19
37,38,6,N,RNROB1,13,14,15,16,16,16,16,17
38,39,6,N,RNROA4,16,18,19,19,19,19,19,19
39,40,6,N,RNROC2,17,19,19,19,19,19,17,19
40,41,6,N,RNROA3,15,18,19,19,19,19,19,19
41,42,6,N,RNROB5,13,16,18,19,19,19,16,17
42,43,6,N,RNROA2,16,17,19,19,18,19,19,19
43,44,6,N,RNROC4,16,18,19,19,19,19,19,19
44,45,6,N,RNROB4,17,18,19,19,19,19,19,19

##### <b> Environmental Variables 1 and 2 </b>

In [9]:
# Environmental variables 1
env_vars_1_df = pd.read_excel("../../raw_data/inside_1.xlsx")

In [10]:
env_vars_1_df.set_index("date", inplace=True)

In [11]:
# List of all the days environment variables 1 were measured
env_1_dates_list = env_vars_1_df.index.unique().tolist()
env_1_dates_list, len(env_1_dates_list)

([Timestamp('2024-08-22 00:00:00'),
  Timestamp('2024-08-23 00:00:00'),
  Timestamp('2024-08-24 00:00:00'),
  Timestamp('2024-08-25 00:00:00'),
  Timestamp('2024-08-26 00:00:00'),
  Timestamp('2024-08-27 00:00:00'),
  Timestamp('2024-08-28 00:00:00'),
  Timestamp('2024-08-29 00:00:00'),
  Timestamp('2024-08-30 00:00:00'),
  Timestamp('2024-08-31 00:00:00'),
  Timestamp('2024-09-01 00:00:00'),
  Timestamp('2024-09-02 00:00:00'),
  Timestamp('2024-09-03 00:00:00'),
  Timestamp('2024-09-04 00:00:00'),
  Timestamp('2024-09-16 00:00:00'),
  Timestamp('2024-09-17 00:00:00'),
  Timestamp('2024-09-18 00:00:00'),
  Timestamp('2024-09-19 00:00:00'),
  Timestamp('2024-09-20 00:00:00'),
  Timestamp('2024-09-21 00:00:00'),
  Timestamp('2024-09-22 00:00:00'),
  Timestamp('2024-09-23 00:00:00'),
  Timestamp('2024-09-24 00:00:00'),
  Timestamp('2024-09-25 00:00:00'),
  Timestamp('2024-09-26 00:00:00'),
  Timestamp('2024-09-27 00:00:00'),
  Timestamp('2024-09-28 00:00:00'),
  Timestamp('2024-09-29 00:00:00'),
  Timestamp('2024-09-30 00:00:00'),
  Timestamp('2024-10-01 00:00:00'),
  Timestamp('2024-10-02 00:00:00'),
  Timestamp('2024-10-03 00:00:00')],
 32)

In [12]:
env_vars_1_df

,timestamp,temperature,humidity,415nm,445nm,480nm,515nm,555nm,590nm,630nm,...,480nm.1,515nm.1,555nm.1,590nm.1,630nm.1,680nm.1,clear.1,nir.1,gain (n),integration (ms)
date,,,,,,,,,,,,,,,,,,,,,
2024-08-22,00:02:04,18.800000,61.400000,0.000000,0.000000,0.000000,0.000000,0.011719,0.031250,0.031250,...,0.0,0.0,3.0,8.0,8.0,2.0,21.0,0.0,10.0,500000.0
2024-08-22,01:02:04,18.300000,64.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003906,0.007812,...,0.0,0.0,0.0,1.0,2.0,0.0,9.0,0.0,10.0,500000.0
2024-08-22,02:02:05,17.400000,68.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015625,0.011719,...,0.0,0.0,0.0,4.0,3.0,0.0,13.0,0.0,10.0,500000.0
2024-08-22,03:02:06,17.300000,71.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019531,0.015625,...,0.0,0.0,0.0,5.0,4.0,0.0,14.0,0.0,10.0,500000.0
2024-08-22,04:02:07,18.000000,74.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011719,0.015625,...,0.0,0.0,0.0,3.0,4.0,1.0,14.0,0.0,10.0,500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,11:02:33,21.564848,86.443733,129.572998,189.802811,228.108200,294.968475,338.299774,338.280945,421.844177,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-03,12:02:27,22.493755,84.966934,271.345673,398.767883,482.346466,623.695374,715.089355,717.434998,896.284546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-03,13:02:27,23.084545,82.951881,268.166809,394.411713,476.071960,614.603455,703.906921,704.613037,879.269714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-03,14:02:28,22.347782,81.459694,194.670502,287.111176,345.562866,445.066803,505.059418,503.463348,627.850342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-03,15:02:28,22.367418,80.730988,169.677185,249.118546,300.181244,388.202972,443.664215,444.076080,555.496338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
env_vars_1_df_temp = env_vars_1_df[['temperature']].copy()

In [14]:
env_vars_1_df_temp['temperature']

date
2024-08-22    18.800000
2024-08-22    18.300000
2024-08-22    17.400000
2024-08-22    17.300000
2024-08-22    18.000000
                ...
2024-10-03    21.564848
2024-10-03    22.493755
2024-10-03    23.084545
2024-10-03    22.347782
2024-10-03    22.367418
Name: temperature, Length: 692, dtype: float64

In [15]:
env_vars_1_df_temp.count()

temperature    692
dtype: int64

In [16]:
env_vars_1_df_temp.isnull().any()

temperature    False
dtype: bool

#### <b> Get the Average and Standard Deviation for Temperature and Humidity for 7 previous day to any given date </b>

In [17]:
daily_temp_1= env_vars_1_df_temp.resample('D').mean()

In [18]:
daily_temp_1

            temperature
date
2024-08-22    20.884000
2024-08-23    24.775000
2024-08-24    22.466667
2024-08-25    24.020833
2024-08-26    24.945833
2024-08-27    20.704167
2024-08-28    20.970833
2024-08-29    21.133333
2024-08-30    22.316667
2024-08-31    20.837500
2024-09-01    22.358333
2024-09-02    21.529167
2024-09-03    21.862500
2024-09-04    19.136364
2024-09-05          NaN
2024-09-06          NaN
2024-09-07          NaN
2024-09-08          NaN
2024-09-09          NaN
2024-09-10          NaN
2024-09-11          NaN
2024-09-12          NaN
2024-09-13          NaN
2024-09-14          NaN
2024-09-15          NaN
2024-09-16    33.722294
2024-09-17    26.678809
2024-09-18    23.183333
2024-09-19    22.175000
2024-09-20    22.794884
2024-09-21    22.287842
2024-09-22    21.377825
2024-09-23    23.785214
2024-09-24    18.885879
2024-09-25    19.707085
2024-09-26    21.815355
2024-09-27    19.495504
2024-09-28    19.723385
2024-09-29    21.277717
2024-09-30    22.463587
2024-10-01    20.655560
2024-10-02    20.381002
2024-10-03    20.414674

In [19]:
daily_temp_1['Weekly Average'] = daily_temp_1['temperature'].rolling(window=7).mean().shift(1)

In [20]:
daily_temp_1['Weekly Std Dev'] = daily_temp_1['Weekly Average'].rolling(window=7).std().shift(1)

In [21]:
daily_temp_1

            temperature  Weekly Average  Weekly Std Dev
date
2024-08-22    20.884000             NaN             NaN
2024-08-23    24.775000             NaN             NaN
2024-08-24    22.466667             NaN             NaN
2024-08-25    24.020833             NaN             NaN
2024-08-26    24.945833             NaN             NaN
2024-08-27    20.704167             NaN             NaN
2024-08-28    20.970833             NaN             NaN
2024-08-29    21.133333       22.681048             NaN
2024-08-30    22.316667       22.716667             NaN
2024-08-31    20.837500       22.365476             NaN
2024-09-01    22.358333       22.132738             NaN
2024-09-02    21.529167       21.895238             NaN
2024-09-03    21.862500       21.407143             NaN
2024-09-04    19.136364       21.572619             NaN
2024-09-05          NaN       21.310552        0.514593
2024-09-06          NaN             NaN        0.521839
2024-09-07          NaN             NaN             NaN
2024-09-08          NaN             NaN             NaN
2024-09-09          NaN             NaN             NaN
2024-09-10          NaN             NaN             NaN
2024-09-11          NaN             NaN             NaN
2024-09-12          NaN             NaN             NaN
2024-09-13          NaN             NaN             NaN
2024-09-14          NaN             NaN             NaN
2024-09-15          NaN             NaN             NaN
2024-09-16    33.722294             NaN             NaN
2024-09-17    26.678809             NaN             NaN
2024-09-18    23.183333             NaN             NaN
2024-09-19    22.175000             NaN             NaN
2024-09-20    22.794884             NaN             NaN
2024-09-21    22.287842             NaN             NaN
2024-09-22    21.377825             NaN             NaN
2024-09-23    23.785214       24.602855             NaN
2024-09-24    18.885879       23.183272             NaN
2024-09-25    19.707085       22.069997             NaN
2024-09-26    21.815355       21.573390             NaN
2024-09-27    19.495504       21.522012             NaN
2024-09-28    19.723385       21.050672             NaN
2024-09-29    21.277717       20.684321             NaN
2024-09-30    22.463587       20.670020        1.363529
2024-10-01    20.655560       20.481216        0.886103
2024-10-02    20.381002       20.734028        0.587143
2024-10-03    20.414674       20.830301        0.436025

In [22]:
# Environmental variables 2
env_vars_2_df = pd.read_excel("../../raw_data/inside_2.xlsx")

In [23]:
env_vars_2_df.set_index("date", inplace=True)

In [24]:
# List of all the days environment variables 1 were measured
env_2_dates_list = env_vars_2_df.index.unique().tolist()
env_2_dates_list, len(env_2_dates_list)

([Timestamp('2024-08-22 00:00:00'),
  Timestamp('2024-08-23 00:00:00'),
  Timestamp('2024-08-24 00:00:00'),
  Timestamp('2024-08-25 00:00:00'),
  Timestamp('2024-08-26 00:00:00'),
  Timestamp('2024-08-27 00:00:00'),
  Timestamp('2024-08-28 00:00:00'),
  Timestamp('2024-08-29 00:00:00'),
  Timestamp('2024-08-30 00:00:00'),
  Timestamp('2024-08-31 00:00:00'),
  Timestamp('2024-09-01 00:00:00'),
  Timestamp('2024-09-02 00:00:00'),
  Timestamp('2024-09-03 00:00:00'),
  Timestamp('2024-09-04 00:00:00'),
  Timestamp('2024-09-05 00:00:00'),
  Timestamp('2024-09-06 00:00:00'),
  Timestamp('2024-09-07 00:00:00'),
  Timestamp('2024-09-08 00:00:00'),
  Timestamp('2024-09-09 00:00:00'),
  Timestamp('2024-09-10 00:00:00'),
  Timestamp('2024-09-11 00:00:00'),
  Timestamp('2024-09-12 00:00:00'),
  Timestamp('2024-09-13 00:00:00'),
  Timestamp('2024-09-14 00:00:00'),
  Timestamp('2024-09-15 00:00:00'),
  Timestamp('2024-09-16 00:00:00'),
  Timestamp('2024-09-17 00:00:00'),
  Timestamp('2024-09-18 00:00:00'),
  Timestamp('2024-09-19 00:00:00'),
  Timestamp('2024-09-20 00:00:00'),
  Timestamp('2024-09-21 00:00:00'),
  Timestamp('2024-09-22 00:00:00'),
  Timestamp('2024-09-23 00:00:00'),
  Timestamp('2024-09-24 00:00:00'),
  Timestamp('2024-09-25 00:00:00'),
  Timestamp('2024-09-26 00:00:00'),
  Timestamp('2024-09-27 00:00:00'),
  Timestamp('2024-09-28 00:00:00'),
  Timestamp('2024-09-29 00:00:00'),
  Timestamp('2024-09-30 00:00:00'),
  Timestamp('2024-10-01 00:00:00'),
  Timestamp('2024-10-02 00:00:00'),
  Timestamp('2024-10-03 00:00:00')],
 43)

In [25]:
env_vars_2_df_temp = env_vars_2_df[['temperature']].copy()

In [26]:
daily_temp_2 = env_vars_2_df_temp.resample('D').mean()

In [27]:
daily_temp_2

            temperature
date
2024-08-22    20.432000
2024-08-23    23.733333
2024-08-24    21.679167
2024-08-25    22.520833
2024-08-26    23.533333
2024-08-27    20.925000
2024-08-28    20.687500
2024-08-29    20.862500
2024-08-30    21.908333
2024-08-31    20.470833
2024-09-01    22.169565
2024-09-02    21.333333
2024-09-03    21.475000
2024-09-04    22.895833
2024-09-05    20.891667
2024-09-06    17.141667
2024-09-07    19.395833
2024-09-08    20.316667
2024-09-09    20.945833
2024-09-10    21.862500
2024-09-11    21.795833
2024-09-12    22.500000
2024-09-13    27.022222
2024-09-14    24.875000
2024-09-15    26.204167
2024-09-16    26.304484
2024-09-17    27.683356
2024-09-18    24.137346
2024-09-19    22.144817
2024-09-20    22.461708
2024-09-21    21.841243
2024-09-22    20.964041
2024-09-23    22.181454
2024-09-24    18.852833
2024-09-25    19.346362
2024-09-26    20.706527
2024-09-27    18.415186
2024-09-28    18.883275
2024-09-29    20.220413
2024-09-30    21.590389
2024-10-01    20.177505
2024-10-02    19.920671
2024-10-03    19.879193

In [28]:
daily_temp_2['Weekly Average'] = daily_temp_2['temperature'].rolling(window=7).mean().shift(1)

In [29]:
daily_temp_2['Weekly Std Dev'] = daily_temp_2['temperature'].rolling(window=7).std().shift(1)

In [30]:
daily_temp_2

            temperature  Weekly Average  Weekly Std Dev
date
2024-08-22    20.432000             NaN             NaN
2024-08-23    23.733333             NaN             NaN
2024-08-24    21.679167             NaN             NaN
2024-08-25    22.520833             NaN             NaN
2024-08-26    23.533333             NaN             NaN
2024-08-27    20.925000             NaN             NaN
2024-08-28    20.687500             NaN             NaN
2024-08-29    20.862500       21.930167        1.356007
2024-08-30    21.908333       21.991667        1.284618
2024-08-31    20.470833       21.730952        1.032731
2024-09-01    22.169565       21.558333        1.138408
2024-09-02    21.333333       21.508152        1.095856
2024-09-03    21.475000       21.193866        0.638119
2024-09-04    22.895833       21.272438        0.633339
2024-09-05    20.891667       21.587914        0.816833
2024-09-06    17.141667       21.592081        0.812579
2024-09-07    19.395833       20.911128        1.844903
2024-09-08    20.316667       20.757557        1.930422
2024-09-09    20.945833       20.492857        1.828904
2024-09-10    21.862500       20.437500        1.804932
2024-09-11    21.795833       20.492857        1.847495
2024-09-12    22.500000       20.335714        1.644690
2024-09-13    27.022222       20.565476        1.836462
2024-09-14    24.875000       21.976984        2.458189
2024-09-15    26.204167       22.759722        2.370076
2024-09-16    26.304484       23.600794        2.403034
2024-09-17    27.683356       24.366315        2.265921
2024-09-18    24.137346       25.197866        2.261995
2024-09-19    22.144817       25.532368        1.801266
2024-09-20    22.461708       25.481627        1.903050
2024-09-21    21.841243       24.830125        2.061750
2024-09-22    20.964041       24.396732        2.349520
2024-09-23    22.181454       23.648142        2.507167
2024-09-24    18.852833       23.059138        2.250254
2024-09-25    19.346362       21.797635        1.609955
2024-09-26    20.706527       21.113208        1.461001
2024-09-27    18.415186       20.907739        1.391210
2024-09-28    18.883275       20.329664        1.476008
2024-09-29    20.220413       19.907097        1.392170
2024-09-30    21.590389       19.800865        1.324819
2024-10-01    20.177505       19.716427        1.155865
2024-10-02    19.920671       19.905665        1.097897
2024-10-03    19.879193       19.987709        1.070246

In [31]:
weekly_averages = pd.merge(daily_temp_1, daily_temp_2, how='outer', left_index=True, right_index=True, suffixes=('_env1', '_env2'))

In [32]:
weekly_averages.columns

Index(['temperature_env1', 'Weekly Average_env1', 'Weekly Std Dev_env1',
       'temperature_env2', 'Weekly Average_env2', 'Weekly Std Dev_env2'],
      dtype='object')

In [33]:
weekly_averages

,temperature_env1,Weekly Average_env1,Weekly Std Dev_env1,temperature_env2,Weekly Average_env2,Weekly Std Dev_env2
date,,,,,,
2024-08-22,20.884000,NaN,NaN,20.432000,NaN,NaN
2024-08-23,24.775000,NaN,NaN,23.733333,NaN,NaN
2024-08-24,22.466667,NaN,NaN,21.679167,NaN,NaN
2024-08-25,24.020833,NaN,NaN,22.520833,NaN,NaN
2024-08-26,24.945833,NaN,NaN,23.533333,NaN,NaN
2024-08-27,20.704167,NaN,NaN,20.925000,NaN,NaN
2024-08-28,20.970833,NaN,NaN,20.687500,NaN,NaN
2024-08-29,21.133333,22.681048,NaN,20.862500,21.930167,1.356007
2024-08-30,22.316667,22.716667,NaN,21.908333,21.991667,1.284618
2024-08-31,20.837500,22.365476,NaN,20.470833,21.730952,1.032731
2024-09-01,22.358333,22.132738,NaN,22.169565,21.558333,1.138408
2024-09-02,21.529167,21.895238,NaN,21.333333,21.508152,1.095856
2024-09-03,21.862500,21.407143,NaN,21.475000,21.193866,0.638119
2024-09-04,19.136364,21.572619,NaN,22.895833,21.272438,0.633339
2024-09-05,NaN,21.310552,0.514593,20.891667,21.587914,0.816833
2024-09-06,NaN,NaN,0.521839,17.141667,21.592081,0.812579
2024-09-07,NaN,NaN,NaN,19.395833,20.911128,1.844903
2024-09-08,NaN,NaN,NaN,20.316667,20.757557,1.930422
2024-09-09,NaN,NaN,NaN,20.945833,20.492857,1.828904
2024-09-10,NaN,NaN,NaN,21.862500,20.437500,1.804932
2024-09-11,NaN,NaN,NaN,21.795833,20.492857,1.847495
2024-09-12,NaN,NaN,NaN,22.500000,20.335714,1.644690
2024-09-13,NaN,NaN,NaN,27.022222,20.565476,1.836462
2024-09-14,NaN,NaN,NaN,24.875000,21.976984,2.458189
2024-09-15,NaN,NaN,NaN,26.204167,22.759722,2.370076
2024-09-16,33.722294,NaN,NaN,26.304484,23.600794,2.403034
2024-09-17,26.678809,NaN,NaN,27.683356,24.366315,2.265921
2024-09-18,23.183333,NaN,NaN,24.137346,25.197866,2.261995
2024-09-19,22.175000,NaN,NaN,22.144817,25.532368,1.801266
2024-09-20,22.794884,NaN,NaN,22.461708,25.481627,1.903050
2024-09-21,22.287842,NaN,NaN,21.841243,24.830125,2.061750
2024-09-22,21.377825,NaN,NaN,20.964041,24.396732,2.349520
2024-09-23,23.785214,24.602855,NaN,22.181454,23.648142,2.507167
2024-09-24,18.885879,23.183272,NaN,18.852833,23.059138,2.250254
2024-09-25,19.707085,22.069997,NaN,19.346362,21.797635,1.609955
2024-09-26,21.815355,21.573390,NaN,20.706527,21.113208,1.461001
2024-09-27,19.495504,21.522012,NaN,18.415186,20.907739,1.391210
2024-09-28,19.723385,21.050672,NaN,18.883275,20.329664,1.476008
2024-09-29,21.277717,20.684321,NaN,20.220413,19.907097,1.392170
2024-09-30,22.463587,20.670020,1.363529,21.590389,19.800865,1.324819
2024-10-01,20.655560,20.481216,0.886103,20.177505,19.716427,1.155865
2024-10-02,20.381002,20.734028,0.587143,19.920671,19.905665,1.097897
2024-10-03,20.414674,20.830301,0.436025,19.879193,19.987709,1.070246

In [34]:
def combine_average(row, column_1, column_2):
    if pd.notnull(row[column_1]) and pd.notnull(row[column_2]):
        return np.mean([row[column_1], row[column_2]])
    
    elif pd.notnull(row[column_1]) and pd.isnull(row[column_2]):
        return row[column_1]
    
    elif pd.isnull(row[column_1]) and pd.notnull(row[column_2]):
        return row[column_2]

    else:
        return np.nan
    
def combine_std_dev(row, column_1, column_2):
    if pd.notnull(row[column_1]) and pd.notnull(row[column_2]):
        return np.sqrt(
            (row[column_1]**2 + row[column_2]) / 2)
    
    elif pd.notnull(row[column_1]) and pd.isnull(row[column_2]):
        return row[column_1]
    
    elif pd.isnull(row[column_1]) and pd.notnull(row[column_2]):
        return row[column_2]

    else:
        return np.nan

In [35]:
weekly_averages['Combined Temperature Average'] = weekly_averages.apply(combine_average, axis=1, args=('Weekly Average_env1', 'Weekly Average_env2'))

In [36]:
weekly_averages['Combined Temperature Std Dev'] = weekly_averages.apply(combine_std_dev, axis=1, args=('Weekly Std Dev_env1','Weekly Std Dev_env2'))

In [37]:
weekly_averages

,temperature_env1,Weekly Average_env1,Weekly Std Dev_env1,temperature_env2,Weekly Average_env2,Weekly Std Dev_env2,Combined Temperature Average,Combined Temperature Std Dev
date,,,,,,,,
2024-08-22,20.884000,NaN,NaN,20.432000,NaN,NaN,NaN,NaN
2024-08-23,24.775000,NaN,NaN,23.733333,NaN,NaN,NaN,NaN
2024-08-24,22.466667,NaN,NaN,21.679167,NaN,NaN,NaN,NaN
2024-08-25,24.020833,NaN,NaN,22.520833,NaN,NaN,NaN,NaN
2024-08-26,24.945833,NaN,NaN,23.533333,NaN,NaN,NaN,NaN
2024-08-27,20.704167,NaN,NaN,20.925000,NaN,NaN,NaN,NaN
2024-08-28,20.970833,NaN,NaN,20.687500,NaN,NaN,NaN,NaN
2024-08-29,21.133333,22.681048,NaN,20.862500,21.930167,1.356007,22.305607,1.356007
2024-08-30,22.316667,22.716667,NaN,21.908333,21.991667,1.284618,22.354167,1.284618
2024-08-31,20.837500,22.365476,NaN,20.470833,21.730952,1.032731,22.048214,1.032731
2024-09-01,22.358333,22.132738,NaN,22.169565,21.558333,1.138408,21.845536,1.138408
2024-09-02,21.529167,21.895238,NaN,21.333333,21.508152,1.095856,21.701695,1.095856
2024-09-03,21.862500,21.407143,NaN,21.475000,21.193866,0.638119,21.300505,0.638119
2024-09-04,19.136364,21.572619,NaN,22.895833,21.272438,0.633339,21.422528,0.633339
2024-09-05,NaN,21.310552,0.514593,20.891667,21.587914,0.816833,21.449233,0.735404
2024-09-06,NaN,NaN,0.521839,17.141667,21.592081,0.812579,21.592081,0.736510
2024-09-07,NaN,NaN,NaN,19.395833,20.911128,1.844903,20.911128,1.844903
2024-09-08,NaN,NaN,NaN,20.316667,20.757557,1.930422,20.757557,1.930422
2024-09-09,NaN,NaN,NaN,20.945833,20.492857,1.828904,20.492857,1.828904
2024-09-10,NaN,NaN,NaN,21.862500,20.437500,1.804932,20.437500,1.804932
2024-09-11,NaN,NaN,NaN,21.795833,20.492857,1.847495,20.492857,1.847495
2024-09-12,NaN,NaN,NaN,22.500000,20.335714,1.644690,20.335714,1.644690
2024-09-13,NaN,NaN,NaN,27.022222,20.565476,1.836462,20.565476,1.836462
2024-09-14,NaN,NaN,NaN,24.875000,21.976984,2.458189,21.976984,2.458189
2024-09-15,NaN,NaN,NaN,26.204167,22.759722,2.370076,22.759722,2.370076
2024-09-16,33.722294,NaN,NaN,26.304484,23.600794,2.403034,23.600794,2.403034
2024-09-17,26.678809,NaN,NaN,27.683356,24.366315,2.265921,24.366315,2.265921
2024-09-18,23.183333,NaN,NaN,24.137346,25.197866,2.261995,25.197866,2.261995
2024-09-19,22.175000,NaN,NaN,22.144817,25.532368,1.801266,25.532368,1.801266
2024-09-20,22.794884,NaN,NaN,22.461708,25.481627,1.903050,25.481627,1.903050
2024-09-21,22.287842,NaN,NaN,21.841243,24.830125,2.061750,24.830125,2.061750
2024-09-22,21.377825,NaN,NaN,20.964041,24.396732,2.349520,24.396732,2.349520
2024-09-23,23.785214,24.602855,NaN,22.181454,23.648142,2.507167,24.125499,2.507167
2024-09-24,18.885879,23.183272,NaN,18.852833,23.059138,2.250254,23.121205,2.250254
2024-09-25,19.707085,22.069997,NaN,19.346362,21.797635,1.609955,21.933816,1.609955
2024-09-26,21.815355,21.573390,NaN,20.706527,21.113208,1.461001,21.343299,1.461001
2024-09-27,19.495504,21.522012,NaN,18.415186,20.907739,1.391210,21.214875,1.391210
2024-09-28,19.723385,21.050672,NaN,18.883275,20.329664,1.476008,20.690168,1.476008
2024-09-29,21.277717,20.684321,NaN,20.220413,19.907097,1.392170,20.295709,1.392170
2024-09-30,22.463587,20.670020,1.363529,21.590389,19.800865,1.324819,20.235442,1.261751
2024-10-01,20.655560,20.481216,0.886103,20.177505,19.716427,1.155865,20.098821,0.985151
2024-10-02,20.381002,20.734028,0.587143,19.920671,19.905665,1.097897,20.319846,0.849304
2024-10-03,20.414674,20.830301,0.436025,19.879193,19.987709,1.070246,20.409005,0.793840

In [38]:
env_vars_1_df_hum = env_vars_1_df[['humidity']].copy()
env_vars_2_df_hum = env_vars_2_df[['humidity']].copy()

daily_hum_1 = env_vars_1_df_hum.resample('D').mean()
daily_hum_2 = env_vars_2_df_hum.resample('D').mean()

daily_hum_1['Humidity Weekly Average'] = daily_hum_1['humidity'].rolling(window=7).mean().shift(1)
daily_hum_1['Humidity Weekly Std Dev'] = daily_hum_1['humidity'].rolling(window=7).std().shift(1)
daily_hum_2['Humidity Weekly Average'] = daily_hum_2['humidity'].rolling(window=7).mean().shift(1)
daily_hum_2['Humidity Weekly Std Dev'] = daily_hum_2['humidity'].rolling(window=7).std().shift(1)

In [39]:
humidity_averages = pd.merge(daily_hum_1, daily_hum_2, how='outer', left_index=True, right_index=True, suffixes=('_env1', '_env2'))

In [40]:
humidity_averages

,humidity_env1,Humidity Weekly Average_env1,Humidity Weekly Std Dev_env1,humidity_env2,Humidity Weekly Average_env2,Humidity Weekly Std Dev_env2
date,,,,,,
2024-08-22,68.716000,NaN,NaN,69.260000,NaN,NaN
2024-08-23,63.058333,NaN,NaN,64.712500,NaN,NaN
2024-08-24,70.200000,NaN,NaN,71.779167,NaN,NaN
2024-08-25,52.558333,NaN,NaN,57.150000,NaN,NaN
2024-08-26,51.016667,NaN,NaN,55.537500,NaN,NaN
2024-08-27,67.541667,NaN,NaN,64.937500,NaN,NaN
2024-08-28,68.045833,NaN,NaN,67.679167,NaN,NaN
2024-08-29,73.325000,63.019548,7.991967,72.245833,64.436548,6.059541
2024-08-30,66.745833,63.677976,8.698154,65.895833,64.863095,6.541584
2024-08-31,70.958333,64.204762,8.765772,70.870833,65.032143,6.552324
2024-09-01,69.570833,64.313095,8.856432,68.382609,64.902381,6.403747
2024-09-02,71.112500,66.743452,7.288589,69.941667,66.507039,5.477772
2024-09-03,56.125000,69.614286,2.338312,55.233333,68.564777,2.641394
2024-09-04,59.081818,67.983333,5.654663,50.891667,67.178468,5.671259
2024-09-05,NaN,66.702760,6.577807,49.437500,64.780254,8.343942
2024-09-06,NaN,NaN,NaN,60.620833,61.521920,9.336990
2024-09-07,NaN,NaN,NaN,64.704167,60.768349,9.135846
2024-09-08,NaN,NaN,NaN,61.375000,59.887396,8.254090
2024-09-09,NaN,NaN,NaN,63.020833,58.886310,7.436499
2024-09-10,NaN,NaN,NaN,59.370833,57.897619,6.053097
2024-09-11,NaN,NaN,NaN,50.670833,58.488690,5.950718
2024-09-12,NaN,NaN,NaN,60.215789,58.457143,5.998103
2024-09-13,NaN,NaN,NaN,38.950000,59.996898,4.490850
2024-09-14,NaN,NaN,NaN,27.079167,56.901065,9.096700
2024-09-15,NaN,NaN,NaN,30.133333,51.526065,13.679197
2024-09-16,11.257414,NaN,NaN,19.139383,47.062970,14.966270
2024-09-17,26.459264,NaN,NaN,22.851474,40.794191,16.298904
2024-09-18,35.095833,NaN,NaN,37.600062,35.577140,15.167135
2024-09-19,50.295833,NaN,NaN,52.904776,33.709887,13.736315
2024-09-20,63.111250,NaN,NaN,63.694005,32.665457,11.477246
2024-09-21,68.644011,NaN,NaN,67.534396,36.200314,16.462948
2024-09-22,77.373895,NaN,NaN,74.800510,41.979633,19.540546
2024-09-23,55.754606,47.462500,24.156220,57.203523,48.360658,22.146671
2024-09-24,74.663874,53.819242,18.148606,73.262191,53.798392,18.074757
2024-09-25,85.177903,60.705615,14.889631,84.430512,60.999923,13.027371
2024-09-26,77.410567,67.860196,12.348566,81.071135,67.689987,10.850612
2024-09-27,67.026024,71.733730,9.938104,72.361232,71.713753,9.604968
2024-09-28,60.783770,72.292983,9.471197,64.514987,72.951928,8.934053
2024-09-29,59.823559,71.170091,10.396652,62.772159,72.520584,9.304423
2024-09-30,64.875171,68.662901,10.761016,66.681961,70.802248,9.904533
2024-10-01,80.379126,69.965838,9.404219,80.350922,72.156311,8.244349
2024-10-02,87.119493,70.782303,10.102267,86.350148,73.168987,8.818218
2024-10-03,86.568023,71.059673,10.578805,86.349222,73.443221,9.246264

In [41]:
humidity_averages

,humidity_env1,Humidity Weekly Average_env1,Humidity Weekly Std Dev_env1,humidity_env2,Humidity Weekly Average_env2,Humidity Weekly Std Dev_env2
date,,,,,,
2024-08-22,68.716000,NaN,NaN,69.260000,NaN,NaN
2024-08-23,63.058333,NaN,NaN,64.712500,NaN,NaN
2024-08-24,70.200000,NaN,NaN,71.779167,NaN,NaN
2024-08-25,52.558333,NaN,NaN,57.150000,NaN,NaN
2024-08-26,51.016667,NaN,NaN,55.537500,NaN,NaN
2024-08-27,67.541667,NaN,NaN,64.937500,NaN,NaN
2024-08-28,68.045833,NaN,NaN,67.679167,NaN,NaN
2024-08-29,73.325000,63.019548,7.991967,72.245833,64.436548,6.059541
2024-08-30,66.745833,63.677976,8.698154,65.895833,64.863095,6.541584
2024-08-31,70.958333,64.204762,8.765772,70.870833,65.032143,6.552324
2024-09-01,69.570833,64.313095,8.856432,68.382609,64.902381,6.403747
2024-09-02,71.112500,66.743452,7.288589,69.941667,66.507039,5.477772
2024-09-03,56.125000,69.614286,2.338312,55.233333,68.564777,2.641394
2024-09-04,59.081818,67.983333,5.654663,50.891667,67.178468,5.671259
2024-09-05,NaN,66.702760,6.577807,49.437500,64.780254,8.343942
2024-09-06,NaN,NaN,NaN,60.620833,61.521920,9.336990
2024-09-07,NaN,NaN,NaN,64.704167,60.768349,9.135846
2024-09-08,NaN,NaN,NaN,61.375000,59.887396,8.254090
2024-09-09,NaN,NaN,NaN,63.020833,58.886310,7.436499
2024-09-10,NaN,NaN,NaN,59.370833,57.897619,6.053097
2024-09-11,NaN,NaN,NaN,50.670833,58.488690,5.950718
2024-09-12,NaN,NaN,NaN,60.215789,58.457143,5.998103
2024-09-13,NaN,NaN,NaN,38.950000,59.996898,4.490850
2024-09-14,NaN,NaN,NaN,27.079167,56.901065,9.096700
2024-09-15,NaN,NaN,NaN,30.133333,51.526065,13.679197
2024-09-16,11.257414,NaN,NaN,19.139383,47.062970,14.966270
2024-09-17,26.459264,NaN,NaN,22.851474,40.794191,16.298904
2024-09-18,35.095833,NaN,NaN,37.600062,35.577140,15.167135
2024-09-19,50.295833,NaN,NaN,52.904776,33.709887,13.736315
2024-09-20,63.111250,NaN,NaN,63.694005,32.665457,11.477246
2024-09-21,68.644011,NaN,NaN,67.534396,36.200314,16.462948
2024-09-22,77.373895,NaN,NaN,74.800510,41.979633,19.540546
2024-09-23,55.754606,47.462500,24.156220,57.203523,48.360658,22.146671
2024-09-24,74.663874,53.819242,18.148606,73.262191,53.798392,18.074757
2024-09-25,85.177903,60.705615,14.889631,84.430512,60.999923,13.027371
2024-09-26,77.410567,67.860196,12.348566,81.071135,67.689987,10.850612
2024-09-27,67.026024,71.733730,9.938104,72.361232,71.713753,9.604968
2024-09-28,60.783770,72.292983,9.471197,64.514987,72.951928,8.934053
2024-09-29,59.823559,71.170091,10.396652,62.772159,72.520584,9.304423
2024-09-30,64.875171,68.662901,10.761016,66.681961,70.802248,9.904533
2024-10-01,80.379126,69.965838,9.404219,80.350922,72.156311,8.244349
2024-10-02,87.119493,70.782303,10.102267,86.350148,73.168987,8.818218
2024-10-03,86.568023,71.059673,10.578805,86.349222,73.443221,9.246264

In [42]:
weekly_averages = pd.merge(weekly_averages, humidity_averages, how='outer', left_index=True, right_index=True)

In [43]:
weekly_averages

,temperature_env1,Weekly Average_env1,Weekly Std Dev_env1,temperature_env2,Weekly Average_env2,Weekly Std Dev_env2,Combined Temperature Average,Combined Temperature Std Dev,humidity_env1,Humidity Weekly Average_env1,Humidity Weekly Std Dev_env1,humidity_env2,Humidity Weekly Average_env2,Humidity Weekly Std Dev_env2
date,,,,,,,,,,,,,,
2024-08-22,20.884000,NaN,NaN,20.432000,NaN,NaN,NaN,NaN,68.716000,NaN,NaN,69.260000,NaN,NaN
2024-08-23,24.775000,NaN,NaN,23.733333,NaN,NaN,NaN,NaN,63.058333,NaN,NaN,64.712500,NaN,NaN
2024-08-24,22.466667,NaN,NaN,21.679167,NaN,NaN,NaN,NaN,70.200000,NaN,NaN,71.779167,NaN,NaN
2024-08-25,24.020833,NaN,NaN,22.520833,NaN,NaN,NaN,NaN,52.558333,NaN,NaN,57.150000,NaN,NaN
2024-08-26,24.945833,NaN,NaN,23.533333,NaN,NaN,NaN,NaN,51.016667,NaN,NaN,55.537500,NaN,NaN
2024-08-27,20.704167,NaN,NaN,20.925000,NaN,NaN,NaN,NaN,67.541667,NaN,NaN,64.937500,NaN,NaN
2024-08-28,20.970833,NaN,NaN,20.687500,NaN,NaN,NaN,NaN,68.045833,NaN,NaN,67.679167,NaN,NaN
2024-08-29,21.133333,22.681048,NaN,20.862500,21.930167,1.356007,22.305607,1.356007,73.325000,63.019548,7.991967,72.245833,64.436548,6.059541
2024-08-30,22.316667,22.716667,NaN,21.908333,21.991667,1.284618,22.354167,1.284618,66.745833,63.677976,8.698154,65.895833,64.863095,6.541584
2024-08-31,20.837500,22.365476,NaN,20.470833,21.730952,1.032731,22.048214,1.032731,70.958333,64.204762,8.765772,70.870833,65.032143,6.552324
2024-09-01,22.358333,22.132738,NaN,22.169565,21.558333,1.138408,21.845536,1.138408,69.570833,64.313095,8.856432,68.382609,64.902381,6.403747
2024-09-02,21.529167,21.895238,NaN,21.333333,21.508152,1.095856,21.701695,1.095856,71.112500,66.743452,7.288589,69.941667,66.507039,5.477772
2024-09-03,21.862500,21.407143,NaN,21.475000,21.193866,0.638119,21.300505,0.638119,56.125000,69.614286,2.338312,55.233333,68.564777,2.641394
2024-09-04,19.136364,21.572619,NaN,22.895833,21.272438,0.633339,21.422528,0.633339,59.081818,67.983333,5.654663,50.891667,67.178468,5.671259
2024-09-05,NaN,21.310552,0.514593,20.891667,21.587914,0.816833,21.449233,0.735404,NaN,66.702760,6.577807,49.437500,64.780254,8.343942
2024-09-06,NaN,NaN,0.521839,17.141667,21.592081,0.812579,21.592081,0.736510,NaN,NaN,NaN,60.620833,61.521920,9.336990
2024-09-07,NaN,NaN,NaN,19.395833,20.911128,1.844903,20.911128,1.844903,NaN,NaN,NaN,64.704167,60.768349,9.135846
2024-09-08,NaN,NaN,NaN,20.316667,20.757557,1.930422,20.757557,1.930422,NaN,NaN,NaN,61.375000,59.887396,8.254090
2024-09-09,NaN,NaN,NaN,20.945833,20.492857,1.828904,20.492857,1.828904,NaN,NaN,NaN,63.020833,58.886310,7.436499
2024-09-10,NaN,NaN,NaN,21.862500,20.437500,1.804932,20.437500,1.804932,NaN,NaN,NaN,59.370833,57.897619,6.053097
2024-09-11,NaN,NaN,NaN,21.795833,20.492857,1.847495,20.492857,1.847495,NaN,NaN,NaN,50.670833,58.488690,5.950718
2024-09-12,NaN,NaN,NaN,22.500000,20.335714,1.644690,20.335714,1.644690,NaN,NaN,NaN,60.215789,58.457143,5.998103
2024-09-13,NaN,NaN,NaN,27.022222,20.565476,1.836462,20.565476,1.836462,NaN,NaN,NaN,38.950000,59.996898,4.490850
2024-09-14,NaN,NaN,NaN,24.875000,21.976984,2.458189,21.976984,2.458189,NaN,NaN,NaN,27.079167,56.901065,9.096700
2024-09-15,NaN,NaN,NaN,26.204167,22.759722,2.370076,22.759722,2.370076,NaN,NaN,NaN,30.133333,51.526065,13.679197
2024-09-16,33.722294,NaN,NaN,26.304484,23.600794,2.403034,23.600794,2.403034,11.257414,NaN,NaN,19.139383,47.062970,14.966270
2024-09-17,26.678809,NaN,NaN,27.683356,24.366315,2.265921,24.366315,2.265921,26.459264,NaN,NaN,22.851474,40.794191,16.298904
2024-09-18,23.183333,NaN,NaN,24.137346,25.197866,2.261995,25.197866,2.261995,35.095833,NaN,NaN,37.600062,35.577140,15.167135
2024-09-19,22.175000,NaN,NaN,22.144817,25.532368,1.801266,25.532368,1.801266,50.295833,NaN,NaN,52.904776,33.709887,13.736315
2024-09-20,22.794884,NaN,NaN,22.461708,25.481627,1.903050,25.481627,1.903050,63.111250,NaN,NaN,63.694005,32.665457,11.477246
2024-09-21,22.287842,NaN,NaN,21.841243,24.830125,2.061750,24.830125,2.061750,68.644011,NaN,NaN,67.534396,36.200314,16.462948
2024-09-22,21.377825,NaN,NaN,20.964041,24.396732,2.349520,24.396732,2.349520,77.373895,NaN,NaN,74.800510,41.979633,19.540546
2024-09-23,23.785214,24.602855,NaN,22.181454,23.648142,2.507167,24.125499,2.507167,55.754606,47.462500,24.156220,57.203523,48.360658,22.146671
2024-09-24,18.885879,23.183272,NaN,18.852833,23.059138,2.250254,23.121205,2.250254,74.663874,53.819242,18.148606,73.262191,53.798392,18.074757
2024-09-25,19.707085,22.069997,NaN,19.346362,21.797635,1.609955,21.933816,1.609955,85.177903,60.705615,14.889631,84.430512,60.999923,13.027371
2024-09-26,21.815355,21.573390,NaN,20.706527,21.113208,1.461001,21.343299,1.461001,77.410567,67.860196,12.348566,81.071135,67.689987,10.850612
2024-09-27,19.495504,21.522012,NaN,18.415186,20.907739,1.391210,21.214875,1.391210,67.026024,71.733730,9.938104,72.361232,71.713753,9.604968
2024-09-28,19.723385,21.050672,NaN,18.883275,20.329664,1.476008,20.690168,1.476008,60.783770,72.292983,9.471197,64.514987,72.951928,8.934053
2024-09-29,21.277717,20.684321,NaN,20.220413,19.907097,1.392170,20.295709,1.392170,59.823559,71.170091,10.396652,62.772159,72.520584,9.304423
2024-09-30,22.463587,20.670020,1.363529,21.590389,19.800865,1.324819,20.235442,1.261751,64.875171,68.662901,10.761016,66.681961,70.802248,9.904533
2024-10-01,20.655560,20.481216,0.886103,20.177505,19.716427,1.155865,20.098821,0.985151,80.379126,69.965838,9.404219,80.350922,72.156311,8.244349
2024-10-02,20.381002,20.734028,0.587143,19.920671,19.905665,1.097897,20.319846,0.849304,87.119493,70.782303,10.102267,86.350148,73.168987,8.818218
2024-10-03,20.414674,20.830301,0.436025,19.879193,19.987709,1.070246,20.409005,0.793840,86.568023,71.059673,10.578805,86.349222,73.443221,9.246264

In [44]:
weekly_averages['Combined Humidity Average'] = weekly_averages.apply(combine_average, axis=1, args=('Humidity Weekly Average_env1', 'Humidity Weekly Average_env2'))

In [45]:
weekly_averages['Combined Humidity Std Dev'] = weekly_averages.apply(combine_std_dev, axis=1, args=('Humidity Weekly Std Dev_env1', 'Humidity Weekly Std Dev_env2'))

In [46]:
weekly_averages

,temperature_env1,Weekly Average_env1,Weekly Std Dev_env1,temperature_env2,Weekly Average_env2,Weekly Std Dev_env2,Combined Temperature Average,Combined Temperature Std Dev,humidity_env1,Humidity Weekly Average_env1,Humidity Weekly Std Dev_env1,humidity_env2,Humidity Weekly Average_env2,Humidity Weekly Std Dev_env2,Combined Humidity Average,Combined Humidity Std Dev
date,,,,,,,,,,,,,,,,
2024-08-22,20.884000,NaN,NaN,20.432000,NaN,NaN,NaN,NaN,68.716000,NaN,NaN,69.260000,NaN,NaN,NaN,NaN
2024-08-23,24.775000,NaN,NaN,23.733333,NaN,NaN,NaN,NaN,63.058333,NaN,NaN,64.712500,NaN,NaN,NaN,NaN
2024-08-24,22.466667,NaN,NaN,21.679167,NaN,NaN,NaN,NaN,70.200000,NaN,NaN,71.779167,NaN,NaN,NaN,NaN
2024-08-25,24.020833,NaN,NaN,22.520833,NaN,NaN,NaN,NaN,52.558333,NaN,NaN,57.150000,NaN,NaN,NaN,NaN
2024-08-26,24.945833,NaN,NaN,23.533333,NaN,NaN,NaN,NaN,51.016667,NaN,NaN,55.537500,NaN,NaN,NaN,NaN
2024-08-27,20.704167,NaN,NaN,20.925000,NaN,NaN,NaN,NaN,67.541667,NaN,NaN,64.937500,NaN,NaN,NaN,NaN
2024-08-28,20.970833,NaN,NaN,20.687500,NaN,NaN,NaN,NaN,68.045833,NaN,NaN,67.679167,NaN,NaN,NaN,NaN
2024-08-29,21.133333,22.681048,NaN,20.862500,21.930167,1.356007,22.305607,1.356007,73.325000,63.019548,7.991967,72.245833,64.436548,6.059541,63.728048,5.913167
2024-08-30,22.316667,22.716667,NaN,21.908333,21.991667,1.284618,22.354167,1.284618,66.745833,63.677976,8.698154,65.895833,64.863095,6.541584,64.270536,6.410907
2024-08-31,20.837500,22.365476,NaN,20.470833,21.730952,1.032731,22.048214,1.032731,70.958333,64.204762,8.765772,70.870833,65.032143,6.552324,64.618452,6.457209
2024-09-01,22.358333,22.132738,NaN,22.169565,21.558333,1.138408,21.845536,1.138408,69.570833,64.313095,8.856432,68.382609,64.902381,6.403747,64.607738,6.513069
2024-09-02,21.529167,21.895238,NaN,21.333333,21.508152,1.095856,21.701695,1.095856,71.112500,66.743452,7.288589,69.941667,66.507039,5.477772,66.625246,5.413008
2024-09-03,21.862500,21.407143,NaN,21.475000,21.193866,0.638119,21.300505,0.638119,56.125000,69.614286,2.338312,55.233333,68.564777,2.641394,69.089532,2.013591
2024-09-04,19.136364,21.572619,NaN,22.895833,21.272438,0.633339,21.422528,0.633339,59.081818,67.983333,5.654663,50.891667,67.178468,5.671259,67.580901,4.338575
2024-09-05,NaN,21.310552,0.514593,20.891667,21.587914,0.816833,21.449233,0.735404,NaN,66.702760,6.577807,49.437500,64.780254,8.343942,65.741507,5.079935
2024-09-06,NaN,NaN,0.521839,17.141667,21.592081,0.812579,21.592081,0.736510,NaN,NaN,NaN,60.620833,61.521920,9.336990,61.521920,9.336990
2024-09-07,NaN,NaN,NaN,19.395833,20.911128,1.844903,20.911128,1.844903,NaN,NaN,NaN,64.704167,60.768349,9.135846,60.768349,9.135846
2024-09-08,NaN,NaN,NaN,20.316667,20.757557,1.930422,20.757557,1.930422,NaN,NaN,NaN,61.375000,59.887396,8.254090,59.887396,8.254090
2024-09-09,NaN,NaN,NaN,20.945833,20.492857,1.828904,20.492857,1.828904,NaN,NaN,NaN,63.020833,58.886310,7.436499,58.886310,7.436499
2024-09-10,NaN,NaN,NaN,21.862500,20.437500,1.804932,20.437500,1.804932,NaN,NaN,NaN,59.370833,57.897619,6.053097,57.897619,6.053097
2024-09-11,NaN,NaN,NaN,21.795833,20.492857,1.847495,20.492857,1.847495,NaN,NaN,NaN,50.670833,58.488690,5.950718,58.488690,5.950718
2024-09-12,NaN,NaN,NaN,22.500000,20.335714,1.644690,20.335714,1.644690,NaN,NaN,NaN,60.215789,58.457143,5.998103,58.457143,5.998103
2024-09-13,NaN,NaN,NaN,27.022222,20.565476,1.836462,20.565476,1.836462,NaN,NaN,NaN,38.950000,59.996898,4.490850,59.996898,4.490850
2024-09-14,NaN,NaN,NaN,24.875000,21.976984,2.458189,21.976984,2.458189,NaN,NaN,NaN,27.079167,56.901065,9.096700,56.901065,9.096700
2024-09-15,NaN,NaN,NaN,26.204167,22.759722,2.370076,22.759722,2.370076,NaN,NaN,NaN,30.133333,51.526065,13.679197,51.526065,13.679197
2024-09-16,33.722294,NaN,NaN,26.304484,23.600794,2.403034,23.600794,2.403034,11.257414,NaN,NaN,19.139383,47.062970,14.966270,47.062970,14.966270
2024-09-17,26.678809,NaN,NaN,27.683356,24.366315,2.265921,24.366315,2.265921,26.459264,NaN,NaN,22.851474,40.794191,16.298904,40.794191,16.298904
2024-09-18,23.183333,NaN,NaN,24.137346,25.197866,2.261995,25.197866,2.261995,35.095833,NaN,NaN,37.600062,35.577140,15.167135,35.577140,15.167135
2024-09-19,22.175000,NaN,NaN,22.144817,25.532368,1.801266,25.532368,1.801266,50.295833,NaN,NaN,52.904776,33.709887,13.736315,33.709887,13.736315
2024-09-20,22.794884,NaN,NaN,22.461708,25.481627,1.903050,25.481627,1.903050,63.111250,NaN,NaN,63.694005,32.665457,11.477246,32.665457,11.477246
2024-09-21,22.287842,NaN,NaN,21.841243,24.830125,2.061750,24.830125,2.061750,68.644011,NaN,NaN,67.534396,36.200314,16.462948,36.200314,16.462948
2024-09-22,21.377825,NaN,NaN,20.964041,24.396732,2.349520,24.396732,2.349520,77.373895,NaN,NaN,74.800510,41.979633,19.540546,41.979633,19.540546
2024-09-23,23.785214,24.602855,NaN,22.181454,23.648142,2.507167,24.125499,2.507167,55.754606,47.462500,24.156220,57.203523,48.360658,22.146671,47.911579,17.402150
2024-09-24,18.885879,23.183272,NaN,18.852833,23.059138,2.250254,23.121205,2.250254,74.663874,53.819242,18.148606,73.262191,53.798392,18.074757,53.808817,13.180414
2024-09-25,19.707085,22.069997,NaN,19.346362,21.797635,1.609955,21.933816,1.609955,85.177903,60.705615,14.889631,84.430512,60.999923,13.027371,60.852769,10.833478
2024-09-26,21.815355,21.573390,NaN,20.706527,21.113208,1.461001,21.343299,1.461001,77.410567,67.860196,12.348566,81.071135,67.689987,10.850612,67.775092,9.037082
2024-09-27,19.495504,21.522012,NaN,18.415186,20.907739,1.391210,21.214875,1.391210,67.026024,71.733730,9.938104,72.361232,71.713753,9.604968,71.723741,7.361076
2024-09-28,19.723385,21.050672,NaN,18.883275,20.329664,1.476008,20.690168,1.476008,60.783770,72.292983,9.471197,64.514987,72.951928,8.934053,72.622456,7.022735
2024-09-29,21.277717,20.684321,NaN,20.220413,19.907097,1.392170,20.295709,1.392170,59.823559,71.170091,10.396652,62.772159,72.520584,9.304423,71.845338,7.661422
2024-09-30,22.463587,20.670020,1.363529,21.590389,19.800865,1.324819,20.235442,1.261751,64.875171,68.662901,10.761016,66.681961,70.802248,9.904533,69.732575,7.927925
2024-10-01,20.655560,20.481216,0.886103,20.177505,19.716427,1.155865,20.098821,0.985151,80.379126,69.965838,9.404219,80.350922,72.156311,8.244349,71.061075,6.952830
2024-10-02,20.381002,20.734028,0.587143,19.920671,19.905665,1.097897,20.319846,0.849304,87.119493,70.782303,10.102267,86.350148,73.168987,8.818218,71.975645,7.445603
2024-10-03,20.414674,20.830301,0.436025,19.879193,19.987709,1.070246,20.409005,0.793840,86.568023,71.059673,10.578805,86.349222,73.443221,9.246264,72.251447,7.783231

#### <b> Getting Temperature and Humidity for a given day on env_vars_1 and env_vars_2 dataframes </b>

In [47]:
temp_max = env_vars_2_df["2024-09-07":"2024-09-07"]["temperature"].max()
temp_min = env_vars_2_df["2024-09-07":"2024-09-07"]["temperature"].min()
temp_mean = env_vars_2_df["2024-09-07":"2024-09-07"]["temperature"].mean()
temp_max, temp_min, temp_mean

(28.5, 15.4, 19.395833333333332)

In [48]:
hum_max = env_vars_2_df["2024-09-07":"2024-09-07"]["humidity"].max()
hum_min = env_vars_2_df["2024-09-07":"2024-09-07"]["humidity"].min()
hum_mean = env_vars_2_df["2024-09-07":"2024-09-07"]["humidity"].mean()
hum_max, hum_min, hum_mean

(79.5, 44.1, 64.70416666666667)

In [49]:
#Check which biometry dates are in environment 1 variables list
biom_in_env1_dates = []
for date in biom_dates_list:
    if date in env_1_dates_list:
        biom_in_env1_dates.append(date)
biom_in_env1_dates, len(biom_in_env1_dates)

([Timestamp('2024-09-17 00:00:00'),
  Timestamp('2024-09-20 00:00:00'),
  Timestamp('2024-09-24 00:00:00'),
  Timestamp('2024-09-29 00:00:00'),
  Timestamp('2024-10-03 00:00:00')],
 5)

In [50]:
#Check which biometry dates are in environment 2 variables list
biom_in_env2_dates = []
for date in biom_dates_list:
    if date in env_2_dates_list:
        biom_in_env2_dates.append(date)
biom_in_env2_dates, len(biom_in_env2_dates)

([Timestamp('2024-09-07 00:00:00'),
  Timestamp('2024-09-11 00:00:00'),
  Timestamp('2024-09-14 00:00:00'),
  Timestamp('2024-09-17 00:00:00'),
  Timestamp('2024-09-20 00:00:00'),
  Timestamp('2024-09-24 00:00:00'),
  Timestamp('2024-09-29 00:00:00'),
  Timestamp('2024-10-03 00:00:00')],
 8)

In [51]:
# Adding columns for Temperature
biometric_df["Max. Temp."] = np.nan
biometric_df["Min. Temp."] = np.nan
biometric_df["Mean Temp."] = np.nan

biometric_df.head(3)

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Thickness 1,Thickness 2,Thickness 3,Thickness 4,Thickness 5,Max. Temp.,Min. Temp.,Mean Temp.
Date,,,,,,,,,,,,,,,,
2024-09-07,1,1,W,RWGRB5,10,"14,5","10,4","9,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09-07,2,1,W,RWGRA3,10,"10,9","9,7","9,8",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09-07,3,1,W,RWGRC1,13,"15,8","13,9","9,4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
# Adding Temperature data from environmental variables 2 dataframe to biometric dataframe
for date in biom_in_env2_dates:

    temp_max = env_vars_2_df[date:date]["temperature"].max()
    temp_min = env_vars_2_df[date:date]["temperature"].min()
    temp_mean = env_vars_2_df[date:date]["temperature"].mean()

    biometric_df.at[date,"Max. Temp."] = temp_max
    biometric_df.at[date,"Min. Temp."] = temp_min
    biometric_df.at[date,"Mean. Temp."] = temp_mean

In [53]:
# Adding columns to biometric_df for Humidity
biometric_df["Max. Hum."] = np.nan
biometric_df["Min. Hum."] = np.nan
biometric_df["Mean Hum."] = np.nan

In [54]:
biometric_df

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Thickness 1,Thickness 2,Thickness 3,Thickness 4,Thickness 5,Max. Temp.,Min. Temp.,Mean Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean Hum.
Date,,,,,,,,,,,,,,,,,,,,
2024-09-07,1,1,W,RWGRB5,10,"14,5","10,4","9,5",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,NaN,19.395833,NaN,NaN,NaN
2024-09-07,2,1,W,RWGRA3,10,"10,9","9,7","9,8",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,NaN,19.395833,NaN,NaN,NaN
2024-09-07,3,1,W,RWGRC1,13,"15,8","13,9","9,4",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,NaN,19.395833,NaN,NaN,NaN
2024-09-07,4,1,W,RWGRA2,10,"12,1","7,2","9,5",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,NaN,19.395833,NaN,NaN,NaN
2024-09-07,5,1,W,RWGRB3,11,"14,2","10,5","12,5",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,NaN,19.395833,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,"26,8","24,5","10,15","0,4","0,32","0,27","0,31",NaN,21.758629,18.687616,NaN,19.879193,NaN,NaN,NaN
2024-10-03,42,6,N,RNROB5,7,"30,1","22,6","11,85","0,32","0,26","0,33","0,37",NaN,21.758629,18.687616,NaN,19.879193,NaN,NaN,NaN
2024-10-03,43,6,N,RNROA2,11,"22,8","20,5","10,35","0,4","0,35","0,39","0,32",NaN,21.758629,18.687616,NaN,19.879193,NaN,NaN,NaN
2024-10-03,44,6,N,RNROC4,10,"30,5","26,2","11,55","0,38","0,32","0,33","0,37",NaN,21.758629,18.687616,NaN,19.879193,NaN,NaN,NaN
2024-10-03,45,6,N,RNROB4,11,"20,6","23,1","9,95","0,43","0,38","0,37","0,35",NaN,21.758629,18.687616,NaN,19.879193,NaN,NaN,NaN

In [55]:
biometric_df.drop(columns='Mean Temp.', inplace=True)

In [56]:
# Adding Humidity data from environmental variables 2 dataframe to biometric dataframe
for date in biom_in_env2_dates:

    hum_max = env_vars_2_df[date:date]["humidity"].max()
    hum_min = env_vars_2_df[date:date]["humidity"].min()
    hum_mean = env_vars_2_df[date:date]["humidity"].mean()

    biometric_df.at[date,"Max. Hum."] = hum_max
    biometric_df.at[date,"Min. Hum."] = hum_min
    biometric_df.at[date,"Mean. Hum."] = hum_mean

In [57]:
biometric_df.drop("Mean Hum.", axis=1, inplace=True)

In [58]:
biometric_df

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Thickness 1,Thickness 2,Thickness 3,Thickness 4,Thickness 5,Max. Temp.,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.
Date,,,,,,,,,,,,,,,,,,,
2024-09-07,1,1,W,RWGRB5,10,"14,5","10,4","9,5",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167
2024-09-07,2,1,W,RWGRA3,10,"10,9","9,7","9,8",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167
2024-09-07,3,1,W,RWGRC1,13,"15,8","13,9","9,4",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167
2024-09-07,4,1,W,RWGRA2,10,"12,1","7,2","9,5",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167
2024-09-07,5,1,W,RWGRB3,11,"14,2","10,5","12,5",NaN,NaN,NaN,NaN,NaN,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,"26,8","24,5","10,15","0,4","0,32","0,27","0,31",NaN,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222
2024-10-03,42,6,N,RNROB5,7,"30,1","22,6","11,85","0,32","0,26","0,33","0,37",NaN,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222
2024-10-03,43,6,N,RNROA2,11,"22,8","20,5","10,35","0,4","0,35","0,39","0,32",NaN,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222
2024-10-03,44,6,N,RNROC4,10,"30,5","26,2","11,55","0,38","0,32","0,33","0,37",NaN,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222
2024-10-03,45,6,N,RNROB4,11,"20,6","23,1","9,95","0,43","0,38","0,37","0,35",NaN,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222

#### <b> Merging weekly_averages and biometric_df </b>

In [59]:
final_biometric = pd.merge(biometric_df, weekly_averages[['Combined Temperature Average', 'Combined Temperature Std Dev','Combined Humidity Average', 'Combined Humidity Std Dev']], how='left', left_index=True , right_index=True)

In [60]:
final_biometric

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Thickness 1,Thickness 2,...,Max. Temp.,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev
2024-09-07,1,1,W,RWGRB5,10,"14,5","10,4","9,5",NaN,NaN,...,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846
2024-09-07,2,1,W,RWGRA3,10,"10,9","9,7","9,8",NaN,NaN,...,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846
2024-09-07,3,1,W,RWGRC1,13,"15,8","13,9","9,4",NaN,NaN,...,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846
2024-09-07,4,1,W,RWGRA2,10,"12,1","7,2","9,5",NaN,NaN,...,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846
2024-09-07,5,1,W,RWGRB3,11,"14,2","10,5","12,5",NaN,NaN,...,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,"26,8","24,5","10,15","0,4","0,32",...,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231
2024-10-03,42,6,N,RNROB5,7,"30,1","22,6","11,85","0,32","0,26",...,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231
2024-10-03,43,6,N,RNROA2,11,"22,8","20,5","10,35","0,4","0,35",...,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231
2024-10-03,44,6,N,RNROC4,10,"30,5","26,2","11,55","0,38","0,32",...,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231
2024-10-03,45,6,N,RNROB4,11,"20,6","23,1","9,95","0,43","0,38",...,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231

##### <b> Getting the BBCH labels and adding it to the Biometric dataframe </b>

In [61]:
bbch_labels_df.columns

Index([           'Number',              'Line',            'Sample',
                    'CODE', 2024-09-07 00:00:00, 2024-09-11 00:00:00,
       2024-09-14 00:00:00, 2024-09-17 00:00:00, 2024-09-20 00:00:00,
       2024-09-24 00:00:00, 2024-09-29 00:00:00, 2024-10-03 00:00:00],
      dtype='object')

In [62]:
date_columns = bbch_labels_df.iloc[:,4:]

In [63]:
# Get the labels for each plant on each day into a list
labels = []
for i in range(0, date_columns.shape[0]):
    for j in range(0,date_columns.shape[1]):
        labels.append(date_columns.iat[i,j])

len(labels)

360

In [64]:
# Turn list into biometric_df column
final_biometric["BBCH"] = labels

In [65]:
final_biometric

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Thickness 1,Thickness 2,...,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH
2024-09-07,1,1,W,RWGRB5,10,"14,5","10,4","9,5",NaN,NaN,...,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19
2024-09-07,2,1,W,RWGRA3,10,"10,9","9,7","9,8",NaN,NaN,...,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19
2024-09-07,3,1,W,RWGRC1,13,"15,8","13,9","9,4",NaN,NaN,...,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19
2024-09-07,4,1,W,RWGRA2,10,"12,1","7,2","9,5",NaN,NaN,...,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19
2024-09-07,5,1,W,RWGRB3,11,"14,2","10,5","12,5",NaN,NaN,...,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,"26,8","24,5","10,15","0,4","0,32",...,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19
2024-10-03,42,6,N,RNROB5,7,"30,1","22,6","11,85","0,32","0,26",...,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19
2024-10-03,43,6,N,RNROA2,11,"22,8","20,5","10,35","0,4","0,35",...,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19
2024-10-03,44,6,N,RNROC4,10,"30,5","26,2","11,55","0,38","0,32",...,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19
2024-10-03,45,6,N,RNROB4,11,"20,6","23,1","9,95","0,43","0,38",...,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19

In [66]:
final_biometric.columns

Index(['Number', 'Line', 'Sample', 'CODE', 'No leaves', 'Diameter',
       'Perpendicular', 'Height', 'Thickness 1', 'Thickness 2', 'Thickness 3',
       'Thickness 4', 'Thickness 5', 'Max. Temp.', 'Min. Temp.', 'Mean. Temp.',
       'Max. Hum.', 'Min. Hum.', 'Mean. Hum.', 'Combined Temperature Average',
       'Combined Temperature Std Dev', 'Combined Humidity Average',
       'Combined Humidity Std Dev', 'BBCH'],
      dtype='object')

In [67]:
final_biometric.isnull()

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Thickness 1,Thickness 2,...,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH
2024-09-07,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
2024-09-07,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
2024-09-07,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
2024-09-07,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
2024-09-07,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2024-10-03,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2024-10-03,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2024-10-03,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2024-10-03,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [68]:
final_biometric.isnull().any()

Number                          False
Line                            False
Sample                          False
CODE                            False
No leaves                       False
Diameter                        False
Perpendicular                   False
Height                          False
Thickness 1                      True
Thickness 2                      True
Thickness 3                      True
Thickness 4                      True
Thickness 5                      True
Max. Temp.                      False
Min. Temp.                      False
Mean. Temp.                     False
Max. Hum.                       False
Min. Hum.                       False
Mean. Hum.                      False
Combined Temperature Average    False
Combined Temperature Std Dev    False
Combined Humidity Average       False
Combined Humidity Std Dev       False
BBCH                            False
dtype: bool

#### <b> Several columns present the decimal separator of numbers as "," but using "." as a decimal separator is prefered </b>

In [69]:
final_biometric["Diameter"] = final_biometric["Diameter"].str.replace(',','.')
final_biometric["Perpendicular"] = final_biometric["Perpendicular"].str.replace(',','.')
final_biometric["Height"] = final_biometric["Height"].str.replace(',','.')

In [70]:
for i in range(1,6):
    column_name = "Thickness %d" %i
    final_biometric[column_name] = biometric_df[column_name].str.replace(',','.')

In [71]:
final_biometric["Diameter"] = pd.to_numeric(final_biometric["Diameter"])
final_biometric["Perpendicular"] = pd.to_numeric(final_biometric["Perpendicular"])
final_biometric["Height"] = pd.to_numeric(final_biometric["Height"])

In [72]:
for i in range(1,6):
    column_name = "Thickness %d" %i
    final_biometric[column_name] = pd.to_numeric(final_biometric[column_name])

#### <b> Average Leaf Thickness </b>

In [73]:
thickness_columns = ['Thickness 1','Thickness 2', 'Thickness 3', 'Thickness 4', 'Thickness 5' ]
final_biometric['Average Leaf Thickness'] = final_biometric[thickness_columns].mean(axis=1)

In [74]:
for i in range(1,6):
    column_name = "Thickness %d" %i
    final_biometric.drop(columns=column_name, inplace=True)

In [75]:
final_biometric

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Max. Temp.,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH,Average Leaf Thickness
2024-09-07,1,1,W,RWGRB5,10,14.5,10.4,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,2,1,W,RWGRA3,10,10.9,9.7,9.80,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,3,1,W,RWGRC1,13,15.8,13.9,9.40,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,4,1,W,RWGRA2,10,12.1,7.2,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,5,1,W,RWGRB3,11,14.2,10.5,12.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,26.8,24.5,10.15,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3250
2024-10-03,42,6,N,RNROB5,7,30.1,22.6,11.85,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3200
2024-10-03,43,6,N,RNROA2,11,22.8,20.5,10.35,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3650
2024-10-03,44,6,N,RNROC4,10,30.5,26.2,11.55,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3500
2024-10-03,45,6,N,RNROB4,11,20.6,23.1,9.95,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3825

#### <b> Rename columns </b>

In [76]:
final_biometric.rename(columns={'Max. Temp.':'Daily Max Temp',
                                'Min. Temp.':'Daily Min Temp',
                                'Mean. Temp.':'Daily Average Temp',
                               'Max. Hum.':'Daily Max Hum',
                                'Min. Hum.':'Daily Min Hum',
                                'Mean. Hum.':'Daily Average Hum',
                                'Combined Temperature Average':'Temperature Average of prior week',
                                'Combined Temperature Std Dev':'Temperature Std Dev of prior week',
                                'Combined Humidity Average':'Humidity Average of prior week',
                                'Combined Humidity Std Dev':'Humidity Std Dev of prior week',
                                'Diameter':'Leaf Diameter',
                                'Perpendicular':'Perpendicular to Leaf Diameter'})

,Number,Line,Sample,CODE,No leaves,Leaf Diameter,Perpendicular to Leaf Diameter,Height,Daily Max Temp,Daily Min Temp,Daily Average Temp,Daily Max Hum,Daily Min Hum,Daily Average Hum,Temperature Average of prior week,Temperature Std Dev of prior week,Humidity Average of prior week,Humidity Std Dev of prior week,BBCH,Average Leaf Thickness
2024-09-07,1,1,W,RWGRB5,10,14.5,10.4,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,2,1,W,RWGRA3,10,10.9,9.7,9.80,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,3,1,W,RWGRC1,13,15.8,13.9,9.40,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,4,1,W,RWGRA2,10,12.1,7.2,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
2024-09-07,5,1,W,RWGRB3,11,14.2,10.5,12.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,26.8,24.5,10.15,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3250
2024-10-03,42,6,N,RNROB5,7,30.1,22.6,11.85,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3200
2024-10-03,43,6,N,RNROA2,11,22.8,20.5,10.35,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3650
2024-10-03,44,6,N,RNROC4,10,30.5,26.2,11.55,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3500
2024-10-03,45,6,N,RNROB4,11,20.6,23.1,9.95,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3825

#### <b> Handle NaN </b>

In [77]:
#Replace Thickness (of leaves) NaN values to 0 
final_biometric.fillna(0, inplace=True)

In [78]:
final_biometric

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Max. Temp.,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH,Average Leaf Thickness
2024-09-07,1,1,W,RWGRB5,10,14.5,10.4,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
2024-09-07,2,1,W,RWGRA3,10,10.9,9.7,9.80,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
2024-09-07,3,1,W,RWGRC1,13,15.8,13.9,9.40,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
2024-09-07,4,1,W,RWGRA2,10,12.1,7.2,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
2024-09-07,5,1,W,RWGRB3,11,14.2,10.5,12.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,26.8,24.5,10.15,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3250
2024-10-03,42,6,N,RNROB5,7,30.1,22.6,11.85,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3200
2024-10-03,43,6,N,RNROA2,11,22.8,20.5,10.35,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3650
2024-10-03,44,6,N,RNROC4,10,30.5,26.2,11.55,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3500
2024-10-03,45,6,N,RNROB4,11,20.6,23.1,9.95,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3825

#### <b> Drop BBCH </b>

In [79]:
final_biometric.drop(columns='BBCH')

,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Max. Temp.,Min. Temp.,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,Average Leaf Thickness
2024-09-07,1,1,W,RWGRB5,10,14.5,10.4,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,0.0000
2024-09-07,2,1,W,RWGRA3,10,10.9,9.7,9.80,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,0.0000
2024-09-07,3,1,W,RWGRC1,13,15.8,13.9,9.40,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,0.0000
2024-09-07,4,1,W,RWGRA2,10,12.1,7.2,9.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,0.0000
2024-09-07,5,1,W,RWGRB3,11,14.2,10.5,12.50,28.500000,15.400000,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-03,41,6,N,RNROA3,11,26.8,24.5,10.15,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,0.3250
2024-10-03,42,6,N,RNROB5,7,30.1,22.6,11.85,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,0.3200
2024-10-03,43,6,N,RNROA2,11,22.8,20.5,10.35,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,0.3650
2024-10-03,44,6,N,RNROC4,10,30.5,26.2,11.55,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,0.3500
2024-10-03,45,6,N,RNROB4,11,20.6,23.1,9.95,21.758629,18.687616,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,0.3825

#### <b> Daily Irrigation </b>

In [80]:
daily_irrigation = pd.read_excel("../raw_data/irrigation.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../raw_data/irrigation.xlsx'

In [79]:
daily_irrigation["Sample"] = daily_irrigation["Sample"].str.upper()

In [80]:
daily_irrigation.set_index("Date", inplace=True)

In [81]:
daily_irrigation

            Sample  Quantity (mL)
Date
2024-08-24  RNGRA1           50.0
2024-08-24  RNGRA2           50.0
2024-08-24  RNGRA3           50.0
2024-08-24  RNGRA4           50.0
2024-08-24  RNGRA5           50.0
...            ...            ...
2024-10-01  RWGRC1            7.5
2024-10-01  RWGRC2           14.5
2024-10-01  RWGRC3            5.0
2024-10-01  RWGRC4           12.0
2024-10-01  RWGRC5            8.0

[990 rows x 2 columns]

##### <b> Join dataframes (daily_irrigation and final_biometric) </b>

In [82]:
final_biometric.reset_index().rename(columns={'index': 'Date'}, inplace=True)

In [83]:
final_biometric.reset_index(inplace=True)

In [84]:
final_biometric.rename(columns={'index': 'Date'}, inplace=True)

In [85]:
final_biometric.head(45)

,Date,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Max. Temp.,...,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH,Average Leaf Thickness
0,2024-09-07,1,1,W,RWGRB5,10,14.5,10.4,9.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
1,2024-09-07,2,1,W,RWGRA3,10,10.9,9.7,9.8,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
2,2024-09-07,3,1,W,RWGRC1,13,15.8,13.9,9.4,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
3,2024-09-07,4,1,W,RWGRA2,10,12.1,7.2,9.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
4,2024-09-07,5,1,W,RWGRB3,11,14.2,10.5,12.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
5,2024-09-07,6,1,W,RWGRA4,10,11.7,9.4,10.1,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,37,0.0
6,2024-09-07,7,1,W,RWGRC3,12,11.1,9.6,11.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,39,0.0
7,2024-09-07,8,1,W,RWGRA5,10,11.3,10.8,7.8,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,44,0.0
8,2024-09-07,9,2,W,RWGRC2,12,15.2,12.1,12.3,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
9,2024-09-07,10,2,W,RWGRB4,10,12.5,13.2,14.6,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
10,2024-09-07,11,2,W,RWGRC5,12,13.1,10.4,12.6,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
11,2024-09-07,12,2,W,RWGRB1,11,12.3,9.8,11.9,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
12,2024-09-07,13,2,W,RWGRC4,11,14.9,12.8,12.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
13,2024-09-07,14,2,W,RWGRB2,7,12.3,7.5,13.2,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
14,2024-09-07,15,2,W,RWGRA1,12,12.4,10.8,11.6,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
15,2024-09-07,16,3,N,RNGRA3,9,9.8,9.7,10.7,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
16,2024-09-07,17,3,N,RNGRB5,12,12.6,12.0,14.2,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
17,2024-09-07,18,3,N,RNGRC4,11,15.2,13.1,10.9,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
18,2024-09-07,19,3,N,RNGRA1,12,12.9,11.1,11.8,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,35,0.0
19,2024-09-07,20,3,N,RNGRC5,12,15.5,12.9,10.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
20,2024-09-07,21,3,N,RNGRB2,10,14.4,12.3,9.4,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
21,2024-09-07,22,3,N,RNGRA2,10,11.6,10.9,9.3,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,37,0.0
22,2024-09-07,23,4,N,RNROB2,6,11.1,8.2,8.7,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,37,0.0
23,2024-09-07,24,4,N,RNROC3,7,11.4,10.2,9.7,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,39,0.0
24,2024-09-07,25,4,N,RNROA5,4,9.7,5.2,8.1,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
25,2024-09-07,26,4,N,RNROC5,7,10.9,8.4,7.6,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
26,2024-09-07,27,4,N,RNROB3,5,11.4,10.2,9.6,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
27,2024-09-07,28,4,N,RNROA1,3,6.5,4.3,5.1,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
28,2024-09-07,29,4,N,RNROC1,5,11.7,7.9,9.2,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
29,2024-09-07,30,5,N,RNGRC1,11,13.4,13.1,13.8,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
30,2024-09-07,31,5,N,RNGRB3,10,13.3,9.5,9.9,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
31,2024-09-07,32,5,N,RNGRA5,7,10.2,6.8,9.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
32,2024-09-07,33,5,N,RNGRB1,9,11.8,9.9,9.4,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
33,2024-09-07,34,5,N,RNGRC3,12,13.8,12.6,10.9,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
34,2024-09-07,35,5,N,RNGRB4,10,11.3,9.8,10.4,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
35,2024-09-07,36,5,N,RNGRA4,7,8.9,7.7,6.9,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
36,2024-09-07,37,5,N,RNGRC2,11,15.4,12.2,12.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
37,2024-09-07,38,6,N,RNROB1,3,6.2,5.1,8.7,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
38,2024-09-07,39,6,N,RNROA4,6,12.2,8.5,10.1,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
39,2024-09-07,40,6,N,RNROC2,7,14.8,12.1,11.3,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
40,2024-09-07,41,6,N,RNROA3,5,12.9,11.2,11.4,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
41,2024-09-07,42,6,N,RNROB5,3,7.3,4.8,9.2,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
42,2024-09-07,43,6,N,RNROA2,6,12.4,10.7,8.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
43,2024-09-07,44,6,N,RNROC4,6,12.1,10.8,11.3,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0
44,2024-09-07,45,6,N,RNROB4,7,13.4,9.7,12.5,28.5,...,19.395833,79.5,44.1,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0

In [86]:
daily_irrigation.reset_index(inplace=True)

In [87]:
daily_irrigation.rename(columns={'index': 'Date', 'Sample':'CODE'}, inplace=True)

In [88]:
di = daily_irrigation['CODE'].unique()

In [89]:
len(daily_irrigation['CODE'].unique())

45

In [90]:
fb = final_biometric['CODE'].unique()

In [91]:
arrays_equal = np.array_equal(np.sort(di), np.sort(fb))

In [92]:
print(arrays_equal)

True

In [93]:
print(np.sort(di))

['RNGRA1' 'RNGRA2' 'RNGRA3' 'RNGRA4' 'RNGRA5' 'RNGRB1' 'RNGRB2' 'RNGRB3'
 'RNGRB4' 'RNGRB5' 'RNGRC1' 'RNGRC2' 'RNGRC3' 'RNGRC4' 'RNGRC5' 'RNROA1'
 'RNROA2' 'RNROA3' 'RNROA4' 'RNROA5' 'RNROB1' 'RNROB2' 'RNROB3' 'RNROB4'
 'RNROB5' 'RNROC1' 'RNROC2' 'RNROC3' 'RNROC4' 'RNROC5' 'RWGRA1' 'RWGRA2'
 'RWGRA3' 'RWGRA4' 'RWGRA5' 'RWGRB1' 'RWGRB2' 'RWGRB3' 'RWGRB4' 'RWGRB5'
 'RWGRC1' 'RWGRC2' 'RWGRC3' 'RWGRC4' 'RWGRC5']

In [94]:
print(np.sort(fb))

['RNGRA1' 'RNGRA2' 'RNGRA3' 'RNGRA4' 'RNGRA5' 'RNGRB1' 'RNGRB2' 'RNGRB3'
 'RNGRB4' 'RNGRB5' 'RNGRC1' 'RNGRC2' 'RNGRC3' 'RNGRC4' 'RNGRC5' 'RNROA1'
 'RNROA2' 'RNROA3' 'RNROA4' 'RNROA5' 'RNROB1' 'RNROB2' 'RNROB3' 'RNROB4'
 'RNROB5' 'RNROC1' 'RNROC2' 'RNROC3' 'RNROC4' 'RNROC5' 'RWGRA1' 'RWGRA2'
 'RWGRA3' 'RWGRA4' 'RWGRA5' 'RWGRB1' 'RWGRB2' 'RWGRB3' 'RWGRB4' 'RWGRB5'
 'RWGRC1' 'RWGRC2' 'RWGRC3' 'RWGRC4' 'RWGRC5']

In [95]:
len(final_biometric['CODE'].unique())

45

In [96]:
daily_irrigation.head(45)

         Date    CODE  Quantity (mL)
0  2024-08-24  RNGRA1           50.0
1  2024-08-24  RNGRA2           50.0
2  2024-08-24  RNGRA3           50.0
3  2024-08-24  RNGRA4           50.0
4  2024-08-24  RNGRA5           50.0
5  2024-08-24  RNGRB1           50.0
6  2024-08-24  RNGRB2           50.0
7  2024-08-24  RNGRB3           50.0
8  2024-08-24  RNGRB4           50.0
9  2024-08-24  RNGRB5           50.0
10 2024-08-24  RNGRC1           50.0
11 2024-08-24  RNGRC2           50.0
12 2024-08-24  RNGRC3           50.0
13 2024-08-24  RNGRC4           50.0
14 2024-08-24  RNGRC5           50.0
15 2024-08-24  RNROA1           50.0
16 2024-08-24  RNROA2           50.0
17 2024-08-24  RNROA3           50.0
18 2024-08-24  RNROA4           50.0
19 2024-08-24  RNROA5           50.0
20 2024-08-24  RNROB1           50.0
21 2024-08-24  RNROB2           50.0
22 2024-08-24  RNROB3           50.0
23 2024-08-24  RNROB4           50.0
24 2024-08-24  RNROB5           50.0
25 2024-08-24  RNROC1           50.0
26 2024-08-24  RNROC2           50.0
27 2024-08-24  RNROC3           50.0
28 2024-08-24  RNROC4           50.0
29 2024-08-24  RNROC5           50.0
30 2024-08-24  RWGRA1           50.0
31 2024-08-24  RWGRA2           50.0
32 2024-08-24  RWGRA3           50.0
33 2024-08-24  RWGRA4           50.0
34 2024-08-24  RWGRA5           50.0
35 2024-08-24  RWGRB1           50.0
36 2024-08-24  RWGRB2           50.0
37 2024-08-24  RWGRB3           50.0
38 2024-08-24  RWGRB4           50.0
39 2024-08-24  RWGRB5           50.0
40 2024-08-24  RWGRC1           50.0
41 2024-08-24  RWGRC2           50.0
42 2024-08-24  RWGRC3           50.0
43 2024-08-24  RWGRC4           50.0
44 2024-08-24  RWGRC5           50.0

In [97]:
merged_biom = pd.merge(final_biometric,
                       daily_irrigation,
                       on=['Date', 'CODE'],
                       how='left')

In [98]:
final_biometric["Date"].unique()

<DatetimeArray>
['2024-09-07 00:00:00', '2024-09-11 00:00:00', '2024-09-14 00:00:00',
 '2024-09-17 00:00:00', '2024-09-20 00:00:00', '2024-09-24 00:00:00',
 '2024-09-29 00:00:00', '2024-10-03 00:00:00']
Length: 8, dtype: datetime64[ns]

In [99]:
final_biometric["Date"].nunique()

8

In [100]:
final_biometric

,Date,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Max. Temp.,...,Mean. Temp.,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH,Average Leaf Thickness
0,2024-09-07,1,1,W,RWGRB5,10,14.5,10.4,9.50,28.500000,...,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
1,2024-09-07,2,1,W,RWGRA3,10,10.9,9.7,9.80,28.500000,...,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
2,2024-09-07,3,1,W,RWGRC1,13,15.8,13.9,9.40,28.500000,...,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
3,2024-09-07,4,1,W,RWGRA2,10,12.1,7.2,9.50,28.500000,...,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
4,2024-09-07,5,1,W,RWGRB3,11,14.2,10.5,12.50,28.500000,...,19.395833,79.50000,44.100000,64.704167,20.911128,1.844903,60.768349,9.135846,19,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2024-10-03,41,6,N,RNROA3,11,26.8,24.5,10.15,21.758629,...,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3250
356,2024-10-03,42,6,N,RNROB5,7,30.1,22.6,11.85,21.758629,...,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3200
357,2024-10-03,43,6,N,RNROA2,11,22.8,20.5,10.35,21.758629,...,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3650
358,2024-10-03,44,6,N,RNROC4,10,30.5,26.2,11.55,21.758629,...,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3500
359,2024-10-03,45,6,N,RNROB4,11,20.6,23.1,9.95,21.758629,...,19.879193,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3825

In [101]:
daily_irrigation["Date"].unique()

<DatetimeArray>
['2024-08-24 00:00:00', '2024-08-26 00:00:00', '2024-08-28 00:00:00',
 '2024-08-30 00:00:00', '2024-09-02 00:00:00', '2024-09-04 00:00:00',
 '2024-09-07 00:00:00', '2024-09-09 00:00:00', '2024-09-11 00:00:00',
 '2024-09-12 00:00:00', '2024-09-13 00:00:00', '2024-09-16 00:00:00',
 '2024-09-17 00:00:00', '2024-09-18 00:00:00', '2024-09-20 00:00:00',
 '2024-09-22 00:00:00', '2024-09-21 00:00:00', '2024-09-23 00:00:00',
 '2024-09-25 00:00:00', '2024-09-26 00:00:00', '2024-09-27 00:00:00',
 '2024-09-30 00:00:00', '2024-10-01 00:00:00']
Length: 23, dtype: datetime64[ns]

In [102]:
daily_irrigation["Date"].nunique()

23

In [109]:
merged_biom[89:]

,Date,Number,Line,Sample,CODE,No leaves,Diameter,Perpendicular,Height,Max. Temp.,...,Max. Hum.,Min. Hum.,Mean. Hum.,Combined Temperature Average,Combined Temperature Std Dev,Combined Humidity Average,Combined Humidity Std Dev,BBCH,Average Leaf Thickness,Quantity (mL)
89,2024-09-11,45,6,N,RNROB4,8,14.6,14.3,12.10,32.900000,...,60.10000,34.100000,50.670833,20.492857,1.847495,58.488690,5.950718,19,0.0000,64.5
90,2024-09-14,1,1,W,RWGRB5,13,19.1,16.8,10.40,36.100000,...,34.80000,18.300000,27.079167,21.976984,2.458189,56.901065,9.096700,19,0.0000,NaN
91,2024-09-14,2,1,W,RWGRA3,13,17.8,15.1,11.30,36.100000,...,34.80000,18.300000,27.079167,21.976984,2.458189,56.901065,9.096700,37,0.0000,NaN
92,2024-09-14,3,1,W,RWGRC1,17,18.1,18.5,9.70,36.100000,...,34.80000,18.300000,27.079167,21.976984,2.458189,56.901065,9.096700,37,0.0000,NaN
93,2024-09-14,4,1,W,RWGRA2,14,16.2,16.5,10.20,36.100000,...,34.80000,18.300000,27.079167,21.976984,2.458189,56.901065,9.096700,39,0.0000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2024-10-03,41,6,N,RNROA3,11,26.8,24.5,10.15,21.758629,...,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3250,NaN
356,2024-10-03,42,6,N,RNROB5,7,30.1,22.6,11.85,21.758629,...,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3200,NaN
357,2024-10-03,43,6,N,RNROA2,11,22.8,20.5,10.35,21.758629,...,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3650,NaN
358,2024-10-03,44,6,N,RNROC4,10,30.5,26.2,11.55,21.758629,...,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3500,NaN
359,2024-10-03,45,6,N,RNROB4,11,20.6,23.1,9.95,21.758629,...,87.61628,81.984047,86.349222,20.409005,0.793840,72.251447,7.783231,19,0.3825,NaN

RO: Read Oak Leaf
GR: Grand Rapid

<b> Fertilização: acrescentar em função da rega com regra de 3 simples </b>

<b> Composição química das plantas: input feature a acrescentar</b>

<b> Peso final das plantas: acrescentar (target variable) </b>

#### <b> Export dataframe to CSV </b>

In [1]:
#biometric_df.to_csv("../data/biometric_data.csv")
#final_biometric.to_csv("../data/final_biometric_data.csv")